services:
  chat:
    build: .
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis
    expose:
      - "8080"
    restart: always
    volumes:
      - ./static:/app/static
      - ./index.html:/app/index.html

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - chat
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/app/static
      - ./index.html:/app/index.html
